/** Cómo se corrige cada issue: instrucción corta para quien edita el código del sitio. */
export const ISSUE_FIX: Record<string, string> = {
  http_4xx: "Restaurar la página o redirigir con 301 a la URL equivalente; quitar los links internos que apuntan aquí.",
  http_5xx: "Error del servidor: revisar el handler/logs de esa ruta.",
  fetch_failed: "No respondió (timeout/conexión): revisar el servidor para esa ruta.",
  blocked_by_waf: "El WAF/Cloudflare bloquea bots: permitir Googlebot y revisar las reglas de bot fight.",
  ssrf_blocked: "La URL apunta a una IP interna: revisar el link.",
  redirect_chain: "Apuntar el primer redirect directo al destino final y actualizar los links internos a la URL final.",
  redirect: "La URL del sitemap redirige: poner en el sitemap la URL final.",
  broken_link: "Link interno a una URL rota (detalle = destino): corregir el href en la página origen o en su plantilla.",
  noindex_in_sitemap: "Página noindex dentro del sitemap: sacarla del sitemap o quitar el noindex.",
  title_missing: "Agregar <title> único y descriptivo (≤ 60 caracteres).",
  title_long: "Acortar el <title> a ≤ 60 caracteres (detalle = largo actual); en plantillas, recortar la parte fija/marca.",
  title_short: "Alargar el <title> con la keyword principal y un calificador (25–60 caracteres).",
  title_dup: "Hacer el <title> único por página (incluir el dato que diferencia: nombre, comuna, categoría, página N).",
  meta_missing: "Agregar meta description única (140–155 caracteres).",
  meta_long: "Recortar la meta description a ≤ 155 caracteres (detalle = largo actual).",
  meta_short: "Ampliar la meta description a 140–155 caracteres.",
  meta_dup: "Hacer la meta description única por página.",
  h1_missing: "Agregar un único <h1> con el tema principal de la página.",
  h1_multiple: "Dejar un solo <h1>; el resto como <h2>.",
  canonical_missing: "Agregar <link rel=\"canonical\"> autorreferente con la URL absoluta.",
  canonical_other: "Canonical apunta a otra URL (detalle = destino): confirmar que sea intencional.",
  jsonld_invalid: "JSON-LD que no parsea: corregir la serialización (comillas, comas, caracteres sin escapar).",
  thin_content: "Menos de 250 palabras (detalle = palabras): ampliar en páginas que deben rankear (categorías, landings); en fichas, sumar texto útil generado desde datos.",
  dup_content: "Contenido idéntico a otras URLs (detalle): diferenciar o canonicalizar a una sola.",
  img_no_alt: "Imágenes sin atributo alt (detalle = cantidad): agregar alt descriptivo en la plantilla.",
  deep_page: "A más de 3 clics de la home: acercarla con links internos (menú, categorías, relacionados).",
  orphan: "Está en el sitemap pero ninguna página la enlaza: agregar links internos desde listados/categorías/relacionados.",
  slow: "Respuesta lenta del servidor (detalle = ms): cachear o optimizar la consulta de esa ruta.",
  no_inlinks: "Sin links entrantes: enlazarla desde páginas relacionadas.",
  robots_missing: "Crear /robots.txt con la URL del sitemap.",
  sitemap_missing: "Crear sitemap.xml y declararlo en robots.txt.",
  blocked_robots: "Bloqueada por robots.txt: confirmar que sea intencional; si debe indexarse, quitar el Disallow.",
  hreflang_no_self: "Agregar el hreflang autorreferente.",
  noindex: "Página con noindex: confirmar que sea intencional.",
};

/** Qué significa cada issue y por qué importa, en una frase. */
export const ISSUE_WHY: Record<string, string> = {
  http_4xx: "La página no existe (404) o está prohibida. Google la saca del índice y los links que llegan a ella se pierden.",
  http_5xx: "El servidor falló al responder. Si se repite, Google baja la frecuencia de rastreo y puede desindexar.",
  fetch_failed: "La página no respondió a tiempo. Para Google es como si no existiera.",
  blocked_by_waf: "Cloudflare u otro firewall bloqueó al crawler. Si también bloquea a Googlebot, esas páginas no se indexan.",
  ssrf_blocked: "El link apunta a una dirección interna que no es pública.",
  redirect_chain: "Varios redirects seguidos: hacen más lenta la carga y pierden fuerza de enlace en cada salto.",
  redirect: "Una URL del sitemap redirige. El sitemap debería listar solo URLs finales.",
  broken_link: "Una página enlaza a otra que da error. Mala experiencia y desperdicio de rastreo.",
  noindex_in_sitemap: "Le pides a Google que la indexe (sitemap) y que no la indexe (noindex) a la vez.",
  title_missing: "Sin <title>: es lo que Google muestra como titular azul en los resultados.",
  title_long: "Más de 60 caracteres: Google lo corta con \"…\" en los resultados.",
  title_short: "Título muy corto: desaprovecha espacio para la keyword y para convencer al clic.",
  title_dup: "Varias páginas con el mismo título: Google no sabe cuál mostrar y compiten entre sí.",
  meta_missing: "Sin meta description: Google inventa el texto bajo el título, a veces mal.",
  meta_long: "Más de ~155 caracteres: Google la corta. No penaliza, solo se ve incompleta.",
  meta_short: "Muy corta: desaprovecha el texto que convence al clic.",
  meta_dup: "Misma descripción en varias páginas: todas se ven iguales en Google.",
  h1_missing: "Sin H1: el encabezado principal le dice a Google y al usuario de qué trata la página.",
  h1_multiple: "Más de un H1: diluye cuál es el tema principal.",
  canonical_missing: "Sin canonical: si la página existe con varias URLs (parámetros, mayúsculas), Google elige la versión por su cuenta.",
  canonical_other: "La página le dice a Google que la versión oficial es otra URL. Esta no va a rankear.",
  jsonld_invalid: "Datos estructurados con error de sintaxis: Google los ignora y pierdes resultados enriquecidos.",
  thin_content: "Menos de 250 palabras: poco texto para que Google entienda el tema y la considere útil.",
  dup_content: "El mismo contenido en varias URLs: compiten entre sí y Google elige una.",
  img_no_alt: "Imágenes sin texto alternativo: Google Imágenes no las entiende y afecta la accesibilidad.",
  deep_page: "A más de 3 clics de la home: Google la rastrea menos y le da menos importancia.",
  orphan: "Está en el sitemap pero ninguna página la enlaza: Google la considera poco importante.",
  slow: "El servidor tarda en responder: afecta la velocidad y cuántas páginas rastrea Google.",
  no_inlinks: "Ninguna página la enlaza: difícil de descubrir para Google y para el usuario.",
  robots_missing: "Sin robots.txt: no es grave, pero es donde se declara el sitemap.",
  sitemap_missing: "Sin sitemap: Google tarda más en descubrir las páginas nuevas.",
  blocked_robots: "robots.txt impide que Google la rastree.",
  hreflang_no_self: "Las versiones por idioma deben incluirse a sí mismas en el hreflang.",
  noindex: "Tiene noindex: Google no la va a mostrar. Bien si es intencional (login, filtros).",
};
